### ISSUE TITLE
game crashed on startup

### ISSUE THREAD

**Issue by Peter111111111111** [Ciastex/ArcadeCoinBugCentral#36]
the game crashed on the "thanks for buying gttod" screen
log is attached 
[output_log.txt](https://github.com/Ciastex/ArcadeCoinBugCentral/files/3989350/output_log.txt)

**Comment by Ciastex** [comment]
The log doesn't tell much, looks like it's truncated... Like the process was killed prematurely. Was there anything else you did that might've crashed the game?

**Comment by Peter111111111111** [comment]
idk it just gave me the blue spinning cursor and then said that gttod stopped working
the only thing that i can think of would maybe be my browser being open but i don't have that many tabs open

**Comment by WobbleOps** [comment]
Does it crash every time when you do that? Have you been able to play at all?

**Comment by Peter111111111111** [comment]
that's actually been the first and only time it crashed at that point
it has crashed twice before during the white screen before the menu and lighter animation show
btw the sound for the lighter sometimes plays before the animation plays

**Comment by WobbleOps** [comment]
The white screen? Like when you are trying to travel to the surface?

I actually believe that the white screen when you are traveling is just the game hanging while loading in. I have had a few moments where it took like 8 or so seconds but then put me into the level. Still, I haven't had a full lock yet, so I can't replicate it.

Also yeah sometimes it does play a bit off. Syncing animation and sound is hard sometimes. I'll work on it some more.

I'm also gonna close this down since a random crash isn't something I can really help out with since they are guaranteed to happen. As long as it isn't a repeatable thing...

Let me know man!
